# next line was auto-created by create-new-analysis; remove this line if you removed the directory.
dirs += HOTVR

# next line was auto-created by create-new-analysis; remove this line if you removed the directory.
dirs += HOTVRStudies
